#!/bin/sh
rm "input_conll1.conll"
# output file conll generated by maltparser exemple: output_conll.conll
rm "output_conll1.conll"
# generate format conll
# $3  : maltparser exemple            : maltparser-1.8.1.jar
# $4  : modele de maltparser exemple  : french.mco
#
#echo "input_conll.conll" #"${Array[0]}"  # 1 --> input_conll.conll --> 1
#echo "output_conll.conll" #"${Array[1]}"  # 2 --> output_conll.conll --> 1
#echo $1  # path_to_maltparser 3 --> 1 --> 2
#echo $2  # str(dict_model_maltparser.get(lang_meta)) 4 --> 2 --> 3
#echo "treetagger_languages"  # "treetagger_languages" 5 --> "treetagger_languages"  --> "treetagger_languages"
#echo $3  # path_to_treetagger 6 --> 3 ---> 4
#echo $4  # path_to_morphtagger 7 --> 4 ---> 5
#echo $5"/home/saber/DA_Stage/treetagger/lib/french-abbreviations" #"${Array[3]}"  # path_to_abbreviations 8 --> 5 --> "None"
#echo $6  # lang_meta 9 --> 6 --> 6
#echo $7 # str(dict_lang_treetagger.get(lang_meta)) 10 --> 7 --> 7
#echo $8 # list_lang 11 --> 8 -->8
#echo $9 # u_txt.strip() 12 --> 9 --> 9
# $5  : treetagger_languages       = sys.argv[1]
# $6  : path_to_treetagger         = sys.argv[2]
# $7  : path to morphtagger for arabic tagging  = sys.argv[3]
# $7  : path_to_abbreviations      = sys.argv[4]
# $8  : langue    : fr,en, ....
# $9  : lang_treetagger
# $10 : list_lang : ['en','fr','it','cs','da','de','el','es','fi','hu','ko','nl','no','pl','pt','ru','sk','sv','tr']
# $11 : texte brut
python generate_conll_input.py "treetagger_languages" $3 $4 $5 $6 $7 $8 "$9" "file_ara1" "result1" "./generate_tag_ara1.sh" > "input_conll1.conll"
# Recuperation des resultats prevenant de MaltParser
java -jar -Xmx4g $1 -c $2 -m parse -i "input_conll1.conll" > "output_conll1.conll"
