[(NN Al>Hd)][(CD 6)][(PUNC /)][(CD 1)][(PUNC /)][(CD 1432)][(NN h)][(PUNC -)][(JJ AlmwAfq)][(CD 12)][(PUNC /)][(CD 12)][(PUNC /)][(CD 2010)][(NN m)][(PUNC ()][(NN |xr)][(NN tHdyv)][(PUNC ))][(NN AlsAEp)][(CD 18)][(PUNC :)][(CD 11)][(PUNC ()][(NNP mkp)][(JJ Almkrmp)][(PUNC ))][(PUNC ,)][(CD 15)][(PUNC :)][(CD 11)][(PUNC ()][(NNP grynt$)][(PUNC ))]
[(PUNC @)][(FW emptyline)][(PUNC @)]
[(NNP >lmAnyA)][(CC w)(NNP Alhnd)][(VBP tTmHAn)][(IN l)(NN zyAdp)][(NN tjArp)(PRPS hmA)]
[(PUNC @)][(FW emptyline)][(PUNC @)]
[(VBD qAlt)][(NNP >lmAnyA)][(CC w)(NNP Alhnd)][(CC <n)(PRP hmA)][(VBP tsthdfAn)][(NN zyAdp)][(NN Hjm)][(NN AltbAdl)][(JJ AltjAry)][(IN byn)(PRP hmA)][(IN xlAl)][(NNS AlEAmyn)][(JJ Almqblyn)][(RP l)(VBP ytjAwz)][(NN AlmstwY)][(JJ AlHAly)][(IN b)(NN nsbp)][(CD 50)][(PUNC %)][(PUNC .)]
[(PUNC @)][(FW emptyline)][(PUNC @)]
[(CC w)(VBD SrHt)][(NN Almst$Arp)][(JJ Al>lmAnyp)][(NNP >njylA)][(NNP myrkl)][(IN fy)][(NN m&tmr)][(NN SHf)(PRPS y)][(NN jmE)(PRPS hA)][(IN b)(NN r}ys)][(NN AlwzrA')][(JJ Alhndy)][(NNP mAnmwhAn)][(NNP syng)][(IN fy)][(NNP brlyn)][(NN Alsbt)][(IN b)(CC >n)][(NNS AlTrfyn)][(VBP yTmHAn)][(IN <lY)][(NN zyAdp)][(NN AltjArp)][(JJ Alsnwyp)][(IN byn)][(NNS Albldyn)][(RP l)(VBP tblg)][(CD 20)][(NN mlyAr)][(NN ywrw)][(PUNC ()][(CD 26)][(PUNC .)][(CD 5)][(NN mlyAr)][(NN dwlAr)][(PUNC ))][(IN b)(NN Hlwl)][(NN EAm)][(CD 2012)][(PUNC .)]
[(PUNC @)][(FW emptyline)][(PUNC @)]
[(CC w)(VBD Ebrt)][(NN Almst$Arp)][(IN En)][(NN vqp)(PRPS hA)][(IN fy)][(CC >n)][(NN {qtSAd)][(NNP Alhnd)][(NN AlmtSAEd)][(VBP sywfr)][(NN frSA)][(VBP tEwd)][(IN b)(NN AlfA}dp)][(IN ElY)][(NNS AlTrfyn)][(PUNC .)]
[(PUNC @)][(FW emptyline)][(PUNC @)]
[(IN mn)][(NN jhp)(PRPS h)][(VBD qAl)][(NNP syng)][(CC <n)][(PUNC ")][(NN tEAwn)(PRPS nA)][(RP lA)][(VBP yErf)][(NN HdwdA)][(PUNC ")]
[(NN m$ydA)][(IN b)(NNS ElAqAt)][(NN blAd)(PRPS h)][(PUNC ")][(JJ Almtmyzp)][(PUNC ")][(IN mE)][(NNP >lmAnyA)][(PUNC .)]
[(PUNC @)][(FW emptyline)][(PUNC @)]
[(CC w)(VBD >DAf)][(CC >n)][(NNP >lmAnyA)][(PRP hy)][(NN mrkz)][(NN Alvql)][(JJ Al{qtSAdy)][(IN fy)][(NNP >wrwbA)][(CC w)(JJ >kbr)][(NN $ryk)][(JJ tjAry)][(IN l)(NNP Alhnd)][(IN fy)][(NN AlqArp)][(PUNC .)]
[(PUNC @)][(FW emptyline)][(PUNC @)]
[(CC w)(VBD {Etbr)][(NNP syng)][(CC >n)][(NN Al{stqrAr)][(JJ Al{qtSAdy)][(IN fy)][(NNP >wrwbA)][(JJ mhm)][(IN l)(NN Al{qtSAd)][(JJ AlEAlmy)][(PUNC ,)][(JJ m$yrA)][(IN <lY)][(NN vqp)(PRPS h)][(IN b)(NN qdrp)][(NN mnTqp)][(NNP Alywrw)][(IN ElY)][(NN tjAwz)][(NN Alm$Akl)][(JJ mhmA)][(VBD kAn)][(NN Hjm)(PRPS hA)][(CC w)(CC >n)(PRP hA)][(VBP stxrj)][(IN mn)(PRP hA)][(NN sAlmp)][(PUNC .)]
[(PUNC @)][(FW emptyline)][(PUNC @)]
[(VBN y$Ar)][(IN <lY)][(CC >n)(PRP h)][(NN wfqA)][(IN l)(NNS byAnAt)][(NN {tHAd)][(NN AlSnAEp)][(JJ Al>lmAny)][(CC f)(CC <n)][(NNP >lmAnyA)][(VBD Sdrt)][(IN b)(JJ DA}E)][(IN b)(NN nHw)][(NN vmAnyp)][(JJ mlyArAt)][(NN ywrw)][(PUNC ()][(CD 10)][(PUNC .)][(CD 6)][(NNS mlyArAt)][(NN dwlAr)][(PUNC ))][(IN <lY)][(NNP Alhnd)][(IN fy)][(CD 2009)][(CC w)(CC >n)][(NN Hjm)][(NN AltjArp)][(JJ Al<jmAly)][(IN byn)][(NNS Albldyn)][(VBD blg)][(CD 13)][(NN mlyAr)][(NN ywrw)][(PUNC ()][(CD 17)][(PUNC .)][(CD 2)][(NN mlyAr)][(NN dwlAr)][(PUNC ))][(IN fy)][(NN nfs)][(JJ AlEAm)][(PUNC .)]
[(PUNC @)][(FW emptyline)][(PUNC @)]
[(CC w)(VBP t>ty)][(NN zyArp)][(NNP syng)][(IN l)(NNP brlyn)][(IN bEd)][(NN zyArp)][(IN l)(NNP brwksl)][(CC Hyv)][(VBD $Ark)][(NN AljmEp)][(IN fy)][(NN qmp)][(NNP Alhnd)][(CC w)(NN Al{tHAd)][(JJ Al>wrwby)][(JJ AlHAdyp)][(JJ E$rp)][(WP Alty)][(VBD {Etbr)][(NNS AlTrfAn)][(IN xlAl)(PRP hA)][(CC >n)(PRP hmA)][(VBP ytqdmAn)][(IN fy)][(NNS AlmbAHvAt)][(IN Hwl)][(NN {tfAq)][(IN l)(NN AltbAdl)][(JJ AltjAry)][(JJ AlHr)][(PUNC .)]
[(PUNC @)][(FW emptyline)][(PUNC @)]
[(CC w)(VBN ytwqE)][(CC >n)][(VBP ysqT)][(NN Al{tfAq)][(IN fy)][(NN HAl)][(NN <brAm)(PRPS h)][(IN nHw)][(CD 90)][(PUNC %)][(IN mn)][(NNS AltEryfAt)][(JJ Aljmrkyp)][(IN byn)][(NNS AlTrfyn)][(PUNC ,)][(CC w)(CC qd)][(VBP t&dy)][(IN l)(NN zyAdp)][(JJ kbyrp)][(IN l)(NN AltbAdl)][(JJ AltjAry)][(WP Alty)][(VBP yblg)][(NN Hjm)(PRPS hA)][(JJ HAlyA)][(IN nHw)][(CD 70)][(NN mlyAr)][(NN ywrw)][(PUNC ()][(CD 92)][(PUNC .)][(CD 6)][(NN mlyAr)][(NN dwlAr)][(PUNC ))][(PUNC .)]
[(PUNC @)][(FW emptyline)][(PUNC @)]
[(CC w)(VBP t$yr)][(NNS tqdyrAt)][(IN <lY)][(CC >n)(PRP h)][(VBP sytm)][(NN AltwqyE)][(IN ElY)][(NN {tfAq)][(IN l)(NN AltjArp)][(JJ AlHrp)][(IN byn)][(NNS AlTrfyn)][(PUNC -)][(WP Al*y)][(VBP yjry)][(NN AltfAwD)][(IN b)(NN $>n)(PRPS h)][(IN mn*)][(CD 2007)][(PUNC -)][(IN fy)][(NN AlrbyE)][(JJ Almqbl)][(PUNC .)]
