#!/bin/sh

# Set these paths appropriately

BIN=/projets/musk/Youtube/ling_youtube/treetagger/bin
CMD=/projets/musk/Youtube/ling_youtube/treetagger/cmd
LIB=/projets/musk/Youtube/ling_youtube/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
PARFILE=${LIB}/slovak-utf8.par

$TOKENIZER $* |
$TAGGER $OPTIONS $PARFILE
