#!/bin/sh

# Set these paths appropriately

BIN=/projets/musk/Youtube/ling_youtube/treetagger/bin
CMD=/projets/musk/Youtube/ling_youtube/treetagger/cmd
LIB=/projets/musk/Youtube/ling_youtube/treetagger/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/tokenize.pl
ABBR_LIST=${LIB}/swahili-abbreviations
PARFILE=${LIB}/swahili.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
