#!/bin/sh

# Set these paths appropriately

BIN=/projets/musk/Youtube/ling_youtube/treetagger/bin
CMD=/projets/musk/Youtube/ling_youtube/treetagger/cmd
LIB=/projets/musk/Youtube/ling_youtube/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
